### ISSUE TITLE
Implement Game and Simulation

### ISSUE THREAD

**Issue by koluacik** [ucanyiit/YATSIM#9]
Specifications:

- Multiple games can be active at the same time.
- Multiple users can be playing in the same map at the same time.
- Concurrency is required.
  * Users should be *notified* on model changes.
  * Users should be able to edit the map concurrently.
  * Users should be able to start and stop the simulation concurrently.
  * Users should be able to toggle stateful game components (junctions etc.) concurrently.
    - Consider the case when a cell is toggled while a train is passing through it.
- Persistency is required. (sqlite, mangodb, or postgresql)

**Comment by ucanyiit** [comment]
Ideas:

- We need a `User` class that has a username. 
  - We can keep joined `Room`s here. So that when a client wants to get which `Room`s they are in, we can respond easily. (Delete, list, copy, share grids)
- We can have a `Room` class.
  - Each `Room` represents a `GameGrid`.
  - Each `Room` has `User`s. It notifies connected `User`s about applied updates.
  - `Room`s receives updates from the `User`s. We can implement a simple locking mechanism on `Room`. So only one `User` will be able to make changes at the same time on a `Room`.
